version: '3'
services:
 ptndown:
  build:
    context: .
    dockerfile: Dockerfile
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  environment:
    PIA_USER: ${PIA_USER}
    PIA_PASS: ${PIA_PASS}
    DBN_PROMETHEUS: ${DBN_PROMETHEUS}
    SP_USERAGENT: ${SP_USERAGENT}
  image: fluxstate/ptndown-pia
  restart: unless-stopped
  ulimits:
    nofile:
      soft: 128000
      hard: 128000
