version: '3'
services:
 ptndown:
  build:
    args:
      PIA_USER: ${PIA_USER}
      PIA_PASS: ${PIA_PASS}
      DBN_PROMETHEUS: ${DBN_PROMETHEUS}
      SP_USERAGENT: ${SP_USERAGENT}
    context: .
    dockerfile: Dockerfile
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  image: fluxstate/ptndown-pia
  ports:
    - "8049/tcp"
  ulimits:
    nofile:
      soft: 128000
      hard: 128000
